- name: Add IP address of all hosts to all hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ item }}$'
    line: "{{ hostvars[item]['ansible_default_ipv4']['address'] }} {{item}}"
    state: present
  when: hostvars[item].inventory_hostname is defined
  with_items: "{{ groups.all }}"

- name: Format Mongodb data disk to XFS
  filesystem:
    fstype: xfs
    dev: /dev/nvme1n1

- name: Mount the Volume to /data
  mount:
    fstype: xfs
    src: /dev/nvme1n1
    path: /data
    state: mounted

- name: Creates directory
  file:
    path: /data/mongodb
    state: directory
    owner: mongodb
    group: mongodb
    
- name: Add MongoDB GPG Key
  shell: wget -qO - https://www.mongodb.org/static/pgp/server-4.4.asc | sudo apt-key add -

- name: Add the APT repository 
  shell: echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/4.4 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.4.list

- name: apt-get update
  apt:
    update_cache: yes

- name: Install Mongodb
  apt:
    name: mongodb-org

- name: Copy mongod.conf file
  template:
    src: mongod.conf.j2
    force: yes
    dest: /etc/mongod.conf
    #owner: mongodb

- name: Make sure Mongod is running
  systemd:
    state: started
    name: mongod
