all:
    hosts:
    children:
        mongodb:
            hosts:
                mongo-0.us-west-1.apiwiz.io:
                    host_name: mongo-0
                    host_ip: "3.101.61.16"
                    host_private_ip: "10.0.6.121"
                mongo-1.us-west-1.apiwiz.io:
                    host_name: mongo-1
                    host_ip: "54.215.210.235"
                    host_private_ip: "10.0.6.144"
                mongo-2.us-west-1.apiwiz.io:
                    host_name: mongo-2
                    host_ip: "54.219.170.81"
                    host_private_ip: "10.0.6.53"
        primary:
            hosts:
                mongo-0.us-west-1.apiwiz.io:
        secondaries:
            hosts:
                mongo-1.us-west-1.apiwiz.io:
                    priority: 1
                mongo-2.us-west-1.apiwiz.io:
                    priority: 1
